spring:
  application:
    name: autoconfiguration


  profiles:
    active: dev

server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: dev


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: true
      generate-ddl: true

  datasource:
    initialize: true

  h2:
    console:
      enabled: true
      path: /h2-console
#
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;DATABASE_TO_UPPER=false
#    username: SA
#    password: q
