spring:
  application:
    name: autoconfiguration


  profiles:
    active: dev

server:
  port: 8082

---

spring:
  config:
    activate:
      on-profile: dev


  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: true
      generate-ddl: true

  h2:
    console:
    # Enable if you use H2 Datasource
      enabled: false
#      enabled: true
      path: /h2-console

  datasource:
    initialize: true

#debug: true
#logging:
#  level:
#    org:
#      springframework : DEBUG
